
project_id = "qapaeujvfgmpuwswxrek"

[functions.ai-chat]
verify_jwt = true

[functions.workflow-executor]
verify_jwt = true

[functions.workflow-execution-engine]
verify_jwt = true

[functions.nl-to-workflow]
verify_jwt = true

[functions.nl-to-n8n]
verify_jwt = true

[functions.integration-manager]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true

[functions.encrypt-credential]
verify_jwt = true

[functions.test-credential]
verify_jwt = true
