// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qapaeujvfgmpuwswxrek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhcGFldWp2ZmdtcHV3c3d4cmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDMwNTAsImV4cCI6MjA2NzAxOTA1MH0.Ug265h_qRkVN9Or1LcM0LIuDU27kcktBLYJ_UBUXqvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});